// Code generated by protoc-gen-go.
// source: test.proto
// DO NOT EDIT!

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	test.proto

It has these top-level messages:
	Company
*/
package main

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Company struct {
	Name             *string             `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Employees        []*Company_Employee `protobuf:"bytes,2,rep,name=employees" json:"employees,omitempty"`
	Country          *string             `protobuf:"bytes,3,opt,name=country" json:"country,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *Company) Reset()         { *m = Company{} }
func (m *Company) String() string { return proto.CompactTextString(m) }
func (*Company) ProtoMessage()    {}

func (m *Company) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Company) GetEmployees() []*Company_Employee {
	if m != nil {
		return m.Employees
	}
	return nil
}

func (m *Company) GetCountry() string {
	if m != nil && m.Country != nil {
		return *m.Country
	}
	return ""
}

type Company_Employee struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Age              *uint32 `protobuf:"varint,2,req,name=age" json:"age,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Company_Employee) Reset()         { *m = Company_Employee{} }
func (m *Company_Employee) String() string { return proto.CompactTextString(m) }
func (*Company_Employee) ProtoMessage()    {}

func (m *Company_Employee) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Company_Employee) GetAge() uint32 {
	if m != nil && m.Age != nil {
		return *m.Age
	}
	return 0
}

func init() {
}
