// Code generated by protoc-gen-go.
// source: test.proto
// DO NOT EDIT!

/*
Package pbs_test is a generated protocol buffer package.

It is generated from these files:
	test.proto

It has these top-level messages:
	TestMessage
*/
package pbs_test

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type TestMessage struct {
	Tsubm            []*TestMessage_TestSubMessage `protobuf:"bytes,1,rep,name=tsubm" json:"tsubm,omitempty"`
	Repint           []int32                       `protobuf:"varint,2,rep,name=repint" json:"repint,omitempty"`
	Repbytes         [][]byte                      `protobuf:"bytes,8,rep,name=repbytes" json:"repbytes,omitempty"`
	Repstring        []string                      `protobuf:"bytes,9,rep,name=repstring" json:"repstring,omitempty"`
	A                *int32                        `protobuf:"varint,3,opt,name=a" json:"a,omitempty"`
	B                *string                       `protobuf:"bytes,4,opt,name=b" json:"b,omitempty"`
	C                *int64                        `protobuf:"varint,5,req,name=c" json:"c,omitempty"`
	D                *bool                         `protobuf:"varint,6,opt,name=d" json:"d,omitempty"`
	E                []byte                        `protobuf:"bytes,7,opt,name=e" json:"e,omitempty"`
	XXX_unrecognized []byte                        `json:"-"`
}

func (m *TestMessage) Reset()         { *m = TestMessage{} }
func (m *TestMessage) String() string { return proto.CompactTextString(m) }
func (*TestMessage) ProtoMessage()    {}

func (m *TestMessage) GetTsubm() []*TestMessage_TestSubMessage {
	if m != nil {
		return m.Tsubm
	}
	return nil
}

func (m *TestMessage) GetRepint() []int32 {
	if m != nil {
		return m.Repint
	}
	return nil
}

func (m *TestMessage) GetRepbytes() [][]byte {
	if m != nil {
		return m.Repbytes
	}
	return nil
}

func (m *TestMessage) GetRepstring() []string {
	if m != nil {
		return m.Repstring
	}
	return nil
}

func (m *TestMessage) GetA() int32 {
	if m != nil && m.A != nil {
		return *m.A
	}
	return 0
}

func (m *TestMessage) GetB() string {
	if m != nil && m.B != nil {
		return *m.B
	}
	return ""
}

func (m *TestMessage) GetC() int64 {
	if m != nil && m.C != nil {
		return *m.C
	}
	return 0
}

func (m *TestMessage) GetD() bool {
	if m != nil && m.D != nil {
		return *m.D
	}
	return false
}

func (m *TestMessage) GetE() []byte {
	if m != nil {
		return m.E
	}
	return nil
}

type TestMessage_TestSubMessage struct {
	X                *string  `protobuf:"bytes,1,opt,name=x" json:"x,omitempty"`
	Y                []uint32 `protobuf:"varint,2,rep,name=y" json:"y,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *TestMessage_TestSubMessage) Reset()         { *m = TestMessage_TestSubMessage{} }
func (m *TestMessage_TestSubMessage) String() string { return proto.CompactTextString(m) }
func (*TestMessage_TestSubMessage) ProtoMessage()    {}

func (m *TestMessage_TestSubMessage) GetX() string {
	if m != nil && m.X != nil {
		return *m.X
	}
	return ""
}

func (m *TestMessage_TestSubMessage) GetY() []uint32 {
	if m != nil {
		return m.Y
	}
	return nil
}

func init() {
}
